# Generated by Django 3.2.6 on 2022-01-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Name', models.CharField(max_length=50)),
                ('Employee_Address', models.CharField(max_length=200)),
                ('Employee_Contact_Number', models.CharField(max_length=15)),
                ('Employee_Email', models.EmailField(max_length=254)),
                ('Employee_Age', models.DateField()),
            ],
        ),
    ]
